- hosts: webapp
  # remote_user: root
  become: yes
  gather_facts: yes

  roles:
    - user.isucon
    - bootstrap
    # - aliyun  # alibaba cloud cli
    - webapp.deploy

    - nginx
    - mysql
    - golang
    # - perl
    # - php
    # - ruby
    # - python
    - nodejs
    - webapp.mysql
    - webapp.golang
    # - webapp.perl
    # - webapp.php
    # - webapp.ruby
    # - webapp.python
    - webapp.nodejs
    - webapp.nginx

  tasks:
    - name: Start default daemons
      become: yes
      become_user: root
      systemd:
        name: "{{ item }}"
        state: restarted
        daemon_reload: yes
        enabled: yes
      with_items:
        - nginx.service
        - mysql.service
        - isucari.nodejs.service
